apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-dev-tquv/appstudio/dc-metro-map@sha256:18f6ea3b32762ed63eaa36980ac01d60b3774c506ae0ca3ea8fe25dc360de1c8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
